version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b24-frontend
    restart: always
    volumes:
      - ./:/frontend
      - /frontend/node_modules
      - /frontend/.next
    ports:
      - 3003:3003
