version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: b24-frontend
    restart: always
    tty: true
    env_file:
      - ../.env
    volumes:
      - ../:/frontend
      - /frontend/node_modules
      - /frontend/.next
    ports:
      - 3003:3003
